### ISSUE TITLE
normalize 0.5.3 contains breaking changes

### ISSUE THREAD

**Issue by pawsong** [gql-dart/ferry#202] opened 2021-06-03 15:47 UTC
Thank you for your contribution to the flutter graphql ecosystem.

I use `graphql-flutter`, which depends on `normalize`. `normalize` 0.5.3 introduced `possibleTypeOf` option, and the new version prevents query results from being cached when `possibleTypeOf` is not supplied. I fixed the issue by rolling back `normalize` version to 0.5.2.

**Comment by smkhalsa** [comment] 2021-06-03 16:31
Hi, thanks for reporting the issue. The `possibleTypes` addition was added as an optional argument to the `(de)normalize` APIs. Do you know which part of the `normalize` API is breaking `graphql-flutter`?

**Comment by ol88** [comment] 2021-06-08 02:58
Hi, I think I'm experiencing the same issue, just updated normalize to 0.5.3 and it's breaking graphql-flutter cache writing of queries.

As an example, here's what's happening to me:

```
I/flutter (17316): Before writing to cache
I/flutter (17316): QueryResult(source: QueryResultSource.network, data: {countries: [{code: AU, id: 1, name: Australia}, {code: US, id: 3, name: United States of America}, {code: FR, id: 2, name: France}]}, context: Context({ResponseExtensions: Instance of 'ResponseExtensions', HttpLinkResponseContext: Instance of 'HttpLinkResponseContext'}), exception: null, timestamp: 2021-06-08 12:22:07.926277)
I/flutter (17316): After re-reading results from cache.
I/flutter (17316): QueryResult(source: QueryResultSource.network, data: {countries: [null, null, null]}, context: Context({ResponseExtensions: Instance of 'ResponseExtensions', HttpLinkResponseContext: Instance of 'HttpLinkResponseContext'}), exception: null, timestamp: 2021-06-08 12:22:07.926277)
```

`{countries: [{code: AU, id: 1, name: Australia}, {code: US, id: 3, name: United States of America}, {code: FR, id: 2, name: France}]}` is passed to normalizeOperation() as data.

When it's re-read from the cache afterwards, it comes back as `{countries: [null, null, null]}`.

I don't know if the write or the read operation is failing but it was working fine in 0.5.2.

**Comment by edson-mgm** [comment] 2021-07-26 16:44
I can confirm the same happens for me.

**Comment by smkhalsa** [comment] 2021-09-06 09:37
closing this since it appears to be an issue with the graphql-flutter library

**Closed by smkhalsa** 2021-09-06 09:37 UTC
