### ISSUE TITLE
How to send Auth Token Header (JWT) 

### ISSUE THREAD

**Issue by arpitjacob** [gql-dart/ferry#95] opened 2020-09-30 00:23 UTC
Looking through Ferrys documentation, I haven't been able to find how to send JWT header token to the client for GraphQL requests that need authentication. 

https://ferrygraphql.com/docs/queries

I have a data layer for my GraphQL queries which is then used in my view models to read/write data. 

Any help or would be appreciated.

**Comment by smkhalsa** [comment] 2020-09-30 08:18
This is configured in the link passed the ferry client. Please see the link below.

https://github.com/gql-dart/gql/blob/1884596904a411363165bcf3c7cfa9dcc2a61c26/examples/gql_example_http_auth_link/lib/http_auth_link.dart

We don't currently have a way to add headers on a request by request basis since ferry requires that OperationRequests can be serializable (to enable features like offline mutations), and the current `Link.Context` API is not serializable.

**Comment by smkhalsa** [comment] 2020-09-30 13:21
NOTE: for request-specific headers, we should be able to add a version of the `gql_exec` Context API to OperationRequest, which can subsequently be passed to the gql_link, provided the user provides their own `built_value` serializer for the Context object.

**Comment by arpitjacob** [comment] 2020-09-30 17:13
Thanks @smkhalsa appreciate the link to the example, I am going to try and implement this today.

**Comment by arpitjacob** [comment] 2020-10-02 09:58
sorry trying to still figure this out, we are using `HttpLink` here to pass the URL which extend `Link` 
```
final link = HttpLink("[path/to/endpoint]");
final client = Client(link: link);
```
The code you linked to you extends `Link` too so how do I pass the Url, or should I be extending `HttpLink`

**Comment by smkhalsa** [comment] 2020-10-13 12:54
I recommend checking out the [Apollo documentation](https://www.apollographql.com/docs/link/overview/) on links to better understand how they work and how to compose them.

gql_link basically works the same way but isn't yet well documented.

**Comment by dunika** [comment] 2020-10-15 15:53
We recently moved from `graphql_flutter/artemis` to `ferry` and I have to say we are having a great time with it 😄 

We were able to set our auth header and make use `ErrorLink` with something similar to the following implementation which builds upon the example that @smkhalsa posted above. Hopefully, this helps a little.

We create the hive store within our main function where we set up our app config and make it available to our app via an Inherited widget.

We use another Inherited widget. to make the graphql client available to our application which takes a `getToken` function which is used to get/update the auth token in our client

```
...
// initialize config
await Hive.initFlutter();
final hiveBox = await Hive.openBox("graphql");
final hiveStore = HiveStore(hiveBox);

return AppConfigData(
  graphQLEndpoint: json['GRAPHQL_ENDPOINT'],
  hiveStore: hiveStore
);
...
```

```
//GraphQlProvider
import 'dart:async';
import 'package:provider/provider.dart';
import 'package:flutter/material.dart';
import 'package:gql_http_link/gql_http_link.dart';
import 'package:ferry/ferry.dart';
import "package:gql_error_link/gql_error_link.dart";
import "package:gql_exec/gql_exec.dart";
import "package:gql_link/gql_link.dart";
import "package:gql_transform_link/gql_transform_link.dart";
import 'package:gql/src/ast/ast.dart';

class HttpAuthLink extends Link {
  Function getToken;
  String graphQLEndpoint;

  String _token;

  Link _link;

  HttpAuthLink({
    this.getToken,
    this.graphQLEndpoint,
  }) {
    _link = Link.from([
      TransformLink(requestTransformer: transformRequest),
      ErrorLink(onException: handleException),
      HttpLink(graphQLEndpoint),
    ]);
  }

  Future<void> updateToken() async {
    _token = await getToken();
  }

  Stream<Response> handleException(
    Request request,
    NextLink forward,
    LinkException exception,
  ) async* {
    if (exception is HttpLinkServerException &&
        exception.response.statusCode == 401) {
      await updateToken();

      yield* forward(request);

      return;
    }

    final message = exception is HttpLinkServerException
      ? exception.response.reasonPhrase
      : exception.toString();

    Zone.current.handleUncaughtError(message, StackTrace.fromString(''));

    throw exception;
  }

  Request transformRequest(Request request) =>
      request.updateContextEntry<HttpLinkHeaders>(
        (headers) => HttpLinkHeaders(
          headers: <String, String>{
            ...headers?.headers ?? <String, String>{},
            "Authorization": _token,
          },
        ),
      );

  @override
  Stream<Response> request(Request request, [forward]) async* {
    if (_token == null) {
      await updateToken();
    }

    yield* _link.request(request, forward);
  }
}

Client initClient({
  @required AppConfigData config,
  @required Function getToken,
}) {

  final cache = Cache(store: config.hiveStore);

  final link = HttpAuthLink(
    graphQLEndpoint: config.graphQLEndpoint,
    getToken: () async {
      String token = await getToken();
      if (token == null) {
        throw NoAuthTokenException("Auth token not set");
      }
      return 'Bearer $token';
    },
  );

  final client = Client(
    link: link,
    cache: cache,
  );

  return client;
}

class GraphQlProvider extends StatelessWidget {
  GraphQlProvider({
    @required this.child,
    @required this.config,
    @required this.getToken,
    String subscriptionUri,
  }) : client = initClient(config: config, getToken: getToken);

  final Widget child;
  final Client client;
  final AppConfigData config;
  final Function getToken;

  static of(BuildContext context) {
    return Provider.of<Client>(context);
  }

  @override
  Widget build(BuildContext context) {
    return Provider<Client>(
      create: (_) => initClient(config: config, getToken: getToken),
      child: child
    );
  }
}

```

**Comment by arpitjacob** [comment] 2020-10-15 16:55
@dunika thanks I switched to the `graphql ` package as I couldn't work out how to make it work. 
Just some feedback. I'll come back to ferry when we have more time. 

We prefer generating our own data classes models The ones generated by `ferry_generated` 
- Were throwing errors
- wasn't intelligent enough to group the same data output results/types 
- no option to rename the class names made our code hard to read. 
- Too many data classes files

**Comment by dunika** [comment] 2020-10-15 17:13
> * wasn't intelligent enough to group the same data output results/types

We also map the response data types to our own models for this very reason. Don't really see a way around this at the moment. `artemis` was the same.

If there was some way that ferry could have shared types across the different queries/mutations that would be amazing! I imagine it would quite tricky though and you would perhaps lose some of the integrity in the types due to different queries selecting different pieces of data.

I think the code gen for the queries/mutations is a pretty big win on its own though

**Comment by smkhalsa** [comment] 2020-10-15 20:23
> If there was some way that ferry could have shared types across the different queries/mutations that would be amazing! I imagine it would quite tricky though and you would perhaps lose some of the integrity in the types due to different queries selecting different pieces of data.

You actually _can_ do this with ferry using fragments. The data types for queries that include fragments implement the fragment's data type.

**Comment by dunika** [comment] 2020-10-15 20:31
@smkhalsa wow, you're a legend! This library is such a game changer 😍

**Comment by TarekkMA** [comment] 2020-10-16 00:52
I have a library that I'm working on that solves this exact issue, it's still WIP but I do use it on my projects. Unfortunately no documentation yet. I plan to finalize it, clean up the code, provide docs, and publish it once I get free to do so.

You can read the source code and the example and decide if you want to use it.
Some features:
- It does integrate with ferry
- Support interfaces
- Support unions with some helper functions (isX, isY) (asX,asY) (xOr, yOr) (when function similar to freezed)
- Scalar conversion
- Generated types have equality and hash code, also it has basic copyWith
But some downsides
- No fragment support
- Cannot represent the graphql (null, not null, omitted)
- Uses old version of ferry (^0.4.1)
- Required dependency_overrides for code_builder (will not be necessary when my PR is merged)

https://github.com/TarekkMA/gql_typed

**Comment by smkhalsa** [comment] 2020-10-16 07:30
@TarekkMA gql_build / ferry_generator already supports unions / interfaces, overrides equality / hash codes and supports scalars and fragments.

I'm curious what's missing for you?

**Comment by arpitjacob** [comment] 2020-10-16 08:08
> You actually _can_ do this with ferry using fragments. The data types for queries that include fragments implement the fragment's data type.

I used fragments for the all the common data. I have a data layer that does all the queries/mutations the response class data type still seem different 

```
final updateUserReq = GupdateUserReq()
```
```
final result = await client.responseStream(updateUserReq).firstWhere((response) => response.dataSource != DataSource.Optimistic);
return result.data.update;
```
This returns `GupdateUserData_update` 

```
final insertUserReq = GinsertUserReq()
```
```
final result = await client.responseStream(insertUserReq).firstWhere((response) => response.dataSource != DataSource.Optimistic);
return result.data.insert;
```
This returns `GinsertUserData_insert` 

Both these mutations return the same data but resulting classnames are different.

**Comment by smkhalsa** [comment] 2020-10-16 08:16
Yes, this is expected.

If you define a fragment with the shared fields and include the fragment in each query, the resulting query data classes will implement the fragment class interface, allowing you to pass data from either query to a component that expects your fragment data class.

Again, you can see how this pattern works in the pokemon example (specifically the PokemonCard widget)

**Comment by arpitjacob** [comment] 2020-10-16 09:25
> We also map the response data types to our own models for this very reason. Don't really see a way around this at the moment. `artemis` was the same.

I guess I'll have to do what @dunika did map the response data types to my own models. Because it doesn't make sense to use different data types for the same response data types also makes it easier to read and reuse across the application.

**Comment by smkhalsa** [comment] 2020-10-16 09:44
@arpitjacob if that makes sense for your application, go for it!

I'm closing this issue since the original topic (i.e. adding headers to links) has been answered.

**Closed by smkhalsa** 2020-10-16 09:44 UTC

**Comment by TarekkMA** [comment] 2020-10-16 12:44
> @TarekkMA gql_build / ferry_generator already supports unions / interfaces, overrides equality / hash codes and supports scalars, fragments, and graphql non nullable types.
> 
> I'm curious what's missing for you?

Oh I wrote this library before you introduced built_value so the overrides equality / hash codes didn't exist.

I'm trying to achieve something similar to this  https://graphql-code-generator.com/ where my data models is generated from schema and use those data models in the gql operation generation and in my code directly without further mapping to my own data models.

**Comment by smkhalsa** [comment] 2020-10-16 13:11
@TarekkMA makes sense.

I've thought about building a fully generated GraphQL client (without needing to create `.graphql` files) from schema, similar to [gqless](https://gqless.dev/). However, there are some pieces of the GraphQL API that are not defined in the schema (e.g. fragments, aliases), and I couldn't figure out how to integrate them into such an architecture. Do you have a vision for how to deal with these (I know you mentioned your solution doesn't currently support fragments)?

This architecture seems like it might be a good fit for some applications, but I figured it wouldn't be suitable as a general-purpose solution unless it supported the entire GraphQL API.

**Comment by friebetill** [comment] 2020-11-04 15:09
The solution from @dunika works for me. But then I had the following errors with some requests:
```
ServerException(originalException: , parsedResponse: null)
ServerException(originalException: Connection closed before full header was received, parsedResponse: null)
ServerException(originalException: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 192.168.0.2, port = 48947, parsedResponse: null)
```
With the help of @knaeckeKami I was able to eliminate the exceptions by using a new `HttpLink` instance for each request:
```dart
import 'dart:async';

import 'package:ferry/ferry.dart';
import 'package:gql_error_link/gql_error_link.dart';
import 'package:gql_exec/gql_exec.dart';
import 'package:gql_http_link/gql_http_link.dart';
import 'package:gql_link/gql_link.dart';
import 'package:gql_transform_link/gql_transform_link.dart';

class HttpAuthLink extends Link {
  HttpAuthLink({this.getToken, this.graphQLEndpoint}) {
    _link = Link.from([
      TransformLink(requestTransformer: transformRequest),
      ErrorLink(onException: handleException),
    ]);
  }

  final String graphQLEndpoint;
  final Future<String> Function() getToken;
  Link _link;
  String _token;

  Future<void> updateToken() async => _token = await getToken();

  Stream<Response> handleException(
    Request request,
    NextLink forward,
    LinkException exception,
  ) async* {
    if (exception is HttpLinkServerException &&
        exception.response.statusCode == 401) {
      await updateToken();
      yield* forward(request);
      return;
    }

    final message = exception is HttpLinkServerException
        ? exception.response.reasonPhrase
        : exception.toString();

    Zone.current.handleUncaughtError(message, StackTrace.fromString(''));

    throw exception;
  }

  Request transformRequest(Request request) {
    return request.updateContextEntry<HttpLinkHeaders>(
      (headers) => HttpLinkHeaders(
        headers: <String, String>{
          ...headers?.headers ?? <String, String>{},
          'Authorization': _token,
        },
      ),
    );
  }

  @override
  Stream<Response> request(
    Request request, [
    Stream<Response> Function(Request) forward,
  ]) async* {
    await updateToken();
    // We have to create a new HttpLink instance every time, because in version
    // 0.3.2 of gql_http_link, there is (probably) a race condition and therefore
    // sometimes one of the three exceptions is thrown when making requests:
    // `ServerException(originalException: , parsedResponse: null)`
    // `ServerException(originalException: Connection closed before full header was received, parsedResponse: null)`
    // `ServerException(originalException: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 192.168.0.1, port = 48947, parsedResponse: null)`
    yield* _link.concat(HttpLink(graphQLEndpoint)).request(request, forward);
  }
}

```

**Comment by m1pl** [comment] 2021-08-14 23:37
@smkhalsa 
> NOTE: for request-specific headers, we should be able to add a version of the `gql_exec` Context API to OperationRequest, which can subsequently be passed to the gql_link, provided the user provides their own `built_value` serializer for the Context object.

Do you have any examples for adding request-specific headers?

**Comment by smkhalsa** [comment] 2021-08-14 23:58
> Do you have any examples for adding request-specific headers?

You'll have to add this logic into your link at the moment.

**Comment by m1pl** [comment] 2021-08-15 08:06
> > Do you have any examples for adding request-specific headers?
> 
> You'll have to add this logic into your link at the moment. 

The problem is that I'm initializing the client outside of a context, which makes writing data from e.g. a bloc on the header impossible with my current structure.

**Comment by elertan** [comment] 2022-02-16 01:38
> The solution from @dunika works for me. But then I had the following errors with some requests:
> 
> ```
> ServerException(originalException: , parsedResponse: null)
> ServerException(originalException: Connection closed before full header was received, parsedResponse: null)
> ServerException(originalException: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 192.168.0.2, port = 48947, parsedResponse: null)
> ```
> 
> With the help of @knaeckeKami I was able to eliminate the exceptions by using a new `HttpLink` instance for each request:
> 
> ```dart
> import 'dart:async';
> 
> import 'package:ferry/ferry.dart';
> import 'package:gql_error_link/gql_error_link.dart';
> import 'package:gql_exec/gql_exec.dart';
> import 'package:gql_http_link/gql_http_link.dart';
> import 'package:gql_link/gql_link.dart';
> import 'package:gql_transform_link/gql_transform_link.dart';
> 
> class HttpAuthLink extends Link {
>   HttpAuthLink({this.getToken, this.graphQLEndpoint}) {
>     _link = Link.from([
>       TransformLink(requestTransformer: transformRequest),
>       ErrorLink(onException: handleException),
>     ]);
>   }
> 
>   final String graphQLEndpoint;
>   final Future<String> Function() getToken;
>   Link _link;
>   String _token;
> 
>   Future<void> updateToken() async => _token = await getToken();
> 
>   Stream<Response> handleException(
>     Request request,
>     NextLink forward,
>     LinkException exception,
>   ) async* {
>     if (exception is HttpLinkServerException &&
>         exception.response.statusCode == 401) {
>       await updateToken();
>       yield* forward(request);
>       return;
>     }
> 
>     final message = exception is HttpLinkServerException
>         ? exception.response.reasonPhrase
>         : exception.toString();
> 
>     Zone.current.handleUncaughtError(message, StackTrace.fromString(''));
> 
>     throw exception;
>   }
> 
>   Request transformRequest(Request request) {
>     return request.updateContextEntry<HttpLinkHeaders>(
>       (headers) => HttpLinkHeaders(
>         headers: <String, String>{
>           ...headers?.headers ?? <String, String>{},
>           'Authorization': _token,
>         },
>       ),
>     );
>   }
> 
>   @override
>   Stream<Response> request(
>     Request request, [
>     Stream<Response> Function(Request) forward,
>   ]) async* {
>     await updateToken();
>     // We have to create a new HttpLink instance every time, because in version
>     // 0.3.2 of gql_http_link, there is (probably) a race condition and therefore
>     // sometimes one of the three exceptions is thrown when making requests:
>     // `ServerException(originalException: , parsedResponse: null)`
>     // `ServerException(originalException: Connection closed before full header was received, parsedResponse: null)`
>     // `ServerException(originalException: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 192.168.0.1, port = 48947, parsedResponse: null)`
>     yield* _link.concat(HttpLink(graphQLEndpoint)).request(request, forward);
>   }
> }
> ```

This is actually very important and fixed my issue.
I was occassionally receiving: `ServerException(originalException: Connection closed before full header was received, parsedResponse: null)`, unsure of whether my graphql api or the mobile app was at fault.
*Create a new instance of the link each time you want to perform a request*

**Comment by GP4cK** [comment] 2023-11-16 05:55
Anyone knows if this race condition was fixed in gql_http_link v1?

**Comment by knaeckeKami** [comment] 2023-11-16 13:17
I don't think there ever was a race condition in the gql_http_link, only issues with the underlying http package and issues with the OS closing connections when the app is in the background. 
see https://github.com/dart-lang/http/issues/197

In my experience, using the cupertiono_http implementation on apple-based systems gets rid of that. I don't yet use cronet_http in production (it did not run on background isolates until recently, but looks like this is supported now).

**Comment by mauro1998** [comment] 2024-11-24 07:48
Alternatively, one can send custom headers per request by adding a `HttpLinkHeaders` entry to the request `Context`.

Here's a quick example:

1. Init your client with `HttpLink`:

```dart
Future<Client> initClient(Config config) async {
  await Hive.initFlutter();
  final box = await Hive.openBox<dynamic>('graphql');
  final store = HiveStore(box);
  final cache = Cache(store: store);
  final link = HttpLink(config.graphqlServerUrl);
  return Client(link: link, cache: cache);
}
```

2. Setup custom `Context` builder utility:

```dart
import 'package:gql_exec/gql_exec.dart'; // <--- needs this package

Context buildContextWithHttpHeaders(Map<String, String> headers) {
  return const Context().withEntry(HttpLinkHeaders(headers: headers));
}
```

3. Provide the `Context` to your request builders:

```dart
final token = await getAuthToken();
final headers = { 'Authorization': 'Bearer $token' };
final request = GSomeReq(
    (builder) => builder
      ..fetchPolicy = FetchPolicy.NetworkOnly
      ..context = buildContextWithHttpHeaders(headers),
);
```

-------------

`HttpLink` will internally retrieve the link headers through the context before executing the requests:

```dart
Map<String, String> _getHttpLinkHeaders(Request request) {
  ...
  final HttpLinkHeaders? linkHeaders = request.context.entry();
  ...
}

http.BaseRequest _prepareRequest(Request request) {
  ...
  final contextHeaders = _getHttpLinkHeaders(request);
  final headers = {
    "Content-type": "application/json",
    "Accept": "*/*",
    ...defaultHeaders,
    ...contextHeaders,
  };
  ...
}
```
