### ISSUE TITLE
Error 403 - Example Code

### ISSUE THREAD

**Issue by eassblack** [gql-dart/ferry#175] opened 2021-04-15 23:58 UTC
Hi, i get this error at run the example code.

"Failed to load resource: the server "https://ferry.us-west-2.aws.cloud.dgraph.io/graphql" responded with a status of 403 ()"

**Comment by smkhalsa** [comment] 2021-04-21 11:53
duplicate of #68

**Closed by smkhalsa** 2021-04-21 11:54 UTC
