### ISSUE TITLE
Class 'GGenerateMutationParamsBuilder' can't define field 'update' and have method 'Builder.update' with the same name.

### ISSUE THREAD

**Issue by aliak00** [gql-dart/ferry#231] opened 2021-07-31 14:36 UTC
Ran the builder on a schema file and got a few errors
![image](https://user-images.githubusercontent.com/2638284/127743067-1c3a6329-bc5e-4e57-8be1-1b78a90edbff.png)

And probably related: `The name 'update' is already defined.`

![image](https://user-images.githubusercontent.com/2638284/127743076-3ae7f47b-8726-475d-bbaa-2e27bffd2b91.png)

And perhaps related to this:
```
Instance members can't be accessed from a factory constructor.
Try removing the reference to the instance member.dart(instance_member_access_from_factory)
The function can't be unconditionally invoked because it can be 'null'.
Try adding a null check ('!').dart(unchecked_use_of_nullable_value)
```

![image](https://user-images.githubusercontent.com/2638284/127743215-5009ed26-5362-4f74-9e34-82469683dbe7.png)

I apologize in advance for the size of the schema file, but it's a generated schema from a much smaller schema. I assume to reproduce the above, create a spanking new flutter app, add the schema below and run the generator:

Schema:
```graphql
#######################
# Input Schema
######################

type User {
	username: String! @id
	displayName: String
	posts(filter: PostFilter, order: PostOrder, first: Int, offset: Int): [Post!] @hasInverse(field: author)
	comments(filter: CommentFilter, order: CommentOrder, first: Int, offset: Int): [Comment!] @hasInverse(field: author)
	postsAggregate(filter: PostFilter): PostAggregateResult
	commentsAggregate(filter: CommentFilter): CommentAggregateResult
}

type Post {
	id: ID!
	title: String! @search(by: [term])
	text: String! @search(by: [fulltext])
	tags: String @search(by: [term])
	datePublished: DateTime
	author(filter: UserFilter): User! @hasInverse(field: posts)
	comments(filter: CommentFilter, order: CommentOrder, first: Int, offset: Int): [Comment!] @hasInverse(field: commentsOn)
	commentsAggregate(filter: CommentFilter): CommentAggregateResult
}

type Comment {
	id: ID!
	text: String!
	commentsOn(filter: PostFilter): Post! @hasInverse(field: comments)
	author(filter: UserFilter): User! @hasInverse(field: comments)
}

#######################
# Extended Definitions
#######################

"""
The Int64 scalar type represents a signed 64‐bit numeric non‐fractional value.
Int64 can represent values in range [-(2^63),(2^63 - 1)].
"""
scalar Int64

"""
The DateTime scalar type represents date and time as a string in RFC3339 format.
For example: "1985-04-12T23:20:50.52Z" represents 20 minutes and 50.52 seconds after the 23rd hour of April 12th, 1985 in UTC.
"""
scalar DateTime

input IntRange{
	min: Int!
	max: Int!
}

input FloatRange{
	min: Float!
	max: Float!
}

input Int64Range{
	min: Int64!
	max: Int64!
}

input DateTimeRange{
	min: DateTime!
	max: DateTime!
}

input StringRange{
	min: String!
	max: String!
}

enum DgraphIndex {
	int
	int64
	float
	bool
	hash
	exact
	term
	fulltext
	trigram
	regexp
	year
	month
	day
	hour
	geo
}

input AuthRule {
	and: [AuthRule]
	or: [AuthRule]
	not: AuthRule
	rule: String
}

enum HTTPMethod {
	GET
	POST
	PUT
	PATCH
	DELETE
}

enum Mode {
	BATCH
	SINGLE
}

input CustomHTTP {
	url: String!
	method: HTTPMethod!
	body: String
	graphql: String
	mode: Mode
	forwardHeaders: [String!]
	secretHeaders: [String!]
	introspectionHeaders: [String!]
	skipIntrospection: Boolean
}

type Point {
	longitude: Float!
	latitude: Float!
}

input PointRef {
	longitude: Float!
	latitude: Float!
}

input NearFilter {
	distance: Float!
	coordinate: PointRef!
}

input PointGeoFilter {
	near: NearFilter
	within: WithinFilter
}

type PointList {
	points: [Point!]!
}

input PointListRef {
	points: [PointRef!]!
}

type Polygon {
	coordinates: [PointList!]!
}

input PolygonRef {
	coordinates: [PointListRef!]!
}

type MultiPolygon {
	polygons: [Polygon!]!
}

input MultiPolygonRef {
	polygons: [PolygonRef!]!
}

input WithinFilter {
	polygon: PolygonRef!
}

input ContainsFilter {
	point: PointRef
	polygon: PolygonRef
}

input IntersectsFilter {
	polygon: PolygonRef
	multiPolygon: MultiPolygonRef
}

input PolygonGeoFilter {
	near: NearFilter
	within: WithinFilter
	contains: ContainsFilter
	intersects: IntersectsFilter
}

input GenerateQueryParams {
	get: Boolean
	query: Boolean
	password: Boolean
	aggregate: Boolean
}

input GenerateMutationParams {
	add: Boolean
	update: Boolean
	delete: Boolean
}

directive @hasInverse(field: String!) on FIELD_DEFINITION
directive @search(by: [DgraphIndex!]) on FIELD_DEFINITION
directive @dgraph(type: String, pred: String) on OBJECT | INTERFACE | FIELD_DEFINITION
directive @id on FIELD_DEFINITION
directive @withSubscription on OBJECT | INTERFACE | FIELD_DEFINITION
directive @secret(field: String!, pred: String) on OBJECT | INTERFACE
directive @auth(
	password: AuthRule
	query: AuthRule,
	add: AuthRule,
	update: AuthRule,
	delete: AuthRule) on OBJECT | INTERFACE
directive @custom(http: CustomHTTP, dql: String) on FIELD_DEFINITION
directive @remote on OBJECT | INTERFACE | UNION | INPUT_OBJECT | ENUM
directive @remoteResponse(name: String) on FIELD_DEFINITION
directive @cascade(fields: [String]) on FIELD
directive @lambda on FIELD_DEFINITION
directive @lambdaOnMutate(add: Boolean, update: Boolean, delete: Boolean) on OBJECT | INTERFACE
directive @cacheControl(maxAge: Int!) on QUERY
directive @generate(
	query: GenerateQueryParams,
	mutation: GenerateMutationParams,
	subscription: Boolean) on OBJECT | INTERFACE

input IntFilter {
	eq: Int
	in: [Int]
	le: Int
	lt: Int
	ge: Int
	gt: Int
	between: IntRange
}

input Int64Filter {
	eq: Int64
	in: [Int64]
	le: Int64
	lt: Int64
	ge: Int64
	gt: Int64
	between: Int64Range
}

input FloatFilter {
	eq: Float
	in: [Float]
	le: Float
	lt: Float
	ge: Float
	gt: Float
	between: FloatRange
}

input DateTimeFilter {
	eq: DateTime
	in: [DateTime]
	le: DateTime
	lt: DateTime
	ge: DateTime
	gt: DateTime
	between: DateTimeRange
}

input StringTermFilter {
	allofterms: String
	anyofterms: String
}

input StringRegExpFilter {
	regexp: String
}

input StringFullTextFilter {
	alloftext: String
	anyoftext: String
}

input StringExactFilter {
	eq: String
	in: [String]
	le: String
	lt: String
	ge: String
	gt: String
	between: StringRange
}

input StringHashFilter {
	eq: String
	in: [String]
}

#######################
# Generated Types
#######################

type AddCommentPayload {
	comment(filter: CommentFilter, order: CommentOrder, first: Int, offset: Int): [Comment]
	numUids: Int
}

type AddPostPayload {
	post(filter: PostFilter, order: PostOrder, first: Int, offset: Int): [Post]
	numUids: Int
}

type AddUserPayload {
	user(filter: UserFilter, order: UserOrder, first: Int, offset: Int): [User]
	numUids: Int
}

type CommentAggregateResult {
	count: Int
	textMin: String
	textMax: String
}

type DeleteCommentPayload {
	comment(filter: CommentFilter, order: CommentOrder, first: Int, offset: Int): [Comment]
	msg: String
	numUids: Int
}

type DeletePostPayload {
	post(filter: PostFilter, order: PostOrder, first: Int, offset: Int): [Post]
	msg: String
	numUids: Int
}

type DeleteUserPayload {
	user(filter: UserFilter, order: UserOrder, first: Int, offset: Int): [User]
	msg: String
	numUids: Int
}

type PostAggregateResult {
	count: Int
	titleMin: String
	titleMax: String
	textMin: String
	textMax: String
	tagsMin: String
	tagsMax: String
	datePublishedMin: DateTime
	datePublishedMax: DateTime
}

type UpdateCommentPayload {
	comment(filter: CommentFilter, order: CommentOrder, first: Int, offset: Int): [Comment]
	numUids: Int
}

type UpdatePostPayload {
	post(filter: PostFilter, order: PostOrder, first: Int, offset: Int): [Post]
	numUids: Int
}

type UpdateUserPayload {
	user(filter: UserFilter, order: UserOrder, first: Int, offset: Int): [User]
	numUids: Int
}

type UserAggregateResult {
	count: Int
	usernameMin: String
	usernameMax: String
	displayNameMin: String
	displayNameMax: String
}

#######################
# Generated Enums
#######################

enum CommentHasFilter {
	text
	commentsOn
	author
}

enum CommentOrderable {
	text
}

enum PostHasFilter {
	title
	text
	tags
	datePublished
	author
	comments
}

enum PostOrderable {
	title
	text
	tags
	datePublished
}

enum UserHasFilter {
	username
	displayName
	posts
	comments
}

enum UserOrderable {
	username
	displayName
}

#######################
# Generated Inputs
#######################

input AddCommentInput {
	text: String!
	commentsOn: PostRef!
	author: UserRef!
}

input AddPostInput {
	title: String!
	text: String!
	tags: String
	datePublished: DateTime
	author: UserRef!
	comments: [CommentRef!]
}

input AddUserInput {
	username: String!
	displayName: String
	posts: [PostRef!]
	comments: [CommentRef!]
}

input CommentFilter {
	id: [ID!]
	has: [CommentHasFilter]
	and: [CommentFilter]
	or: [CommentFilter]
	not: CommentFilter
}

input CommentOrder {
	asc: CommentOrderable
	desc: CommentOrderable
	then: CommentOrder
}

input CommentPatch {
	text: String
	commentsOn: PostRef
	author: UserRef
}

input CommentRef {
	id: ID
	text: String
	commentsOn: PostRef
	author: UserRef
}

input PostFilter {
	id: [ID!]
	title: StringTermFilter
	text: StringFullTextFilter
	tags: StringTermFilter
	has: [PostHasFilter]
	and: [PostFilter]
	or: [PostFilter]
	not: PostFilter
}

input PostOrder {
	asc: PostOrderable
	desc: PostOrderable
	then: PostOrder
}

input PostPatch {
	title: String
	text: String
	tags: String
	datePublished: DateTime
	author: UserRef
	comments: [CommentRef!]
}

input PostRef {
	id: ID
	title: String
	text: String
	tags: String
	datePublished: DateTime
	author: UserRef
	comments: [CommentRef!]
}

input UpdateCommentInput {
	filter: CommentFilter!
	set: CommentPatch
	remove: CommentPatch
}

input UpdatePostInput {
	filter: PostFilter!
	set: PostPatch
	remove: PostPatch
}

input UpdateUserInput {
	filter: UserFilter!
	set: UserPatch
	remove: UserPatch
}

input UserFilter {
	username: StringHashFilter
	has: [UserHasFilter]
	and: [UserFilter]
	or: [UserFilter]
	not: UserFilter
}

input UserOrder {
	asc: UserOrderable
	desc: UserOrderable
	then: UserOrder
}

input UserPatch {
	displayName: String
	posts: [PostRef!]
	comments: [CommentRef!]
}

input UserRef {
	username: String
	displayName: String
	posts: [PostRef!]
	comments: [CommentRef!]
}

#######################
# Generated Query
#######################

type Query {
	getUser(username: String!): User
	queryUser(filter: UserFilter, order: UserOrder, first: Int, offset: Int): [User]
	aggregateUser(filter: UserFilter): UserAggregateResult
	getPost(id: ID!): Post
	queryPost(filter: PostFilter, order: PostOrder, first: Int, offset: Int): [Post]
	aggregatePost(filter: PostFilter): PostAggregateResult
	getComment(id: ID!): Comment
	queryComment(filter: CommentFilter, order: CommentOrder, first: Int, offset: Int): [Comment]
	aggregateComment(filter: CommentFilter): CommentAggregateResult
}

#######################
# Generated Mutations
#######################

type Mutation {
	addUser(input: [AddUserInput!]!, upsert: Boolean): AddUserPayload
	updateUser(input: UpdateUserInput!): UpdateUserPayload
	deleteUser(filter: UserFilter!): DeleteUserPayload
	addPost(input: [AddPostInput!]!): AddPostPayload
	updatePost(input: UpdatePostInput!): UpdatePostPayload
	deletePost(filter: PostFilter!): DeletePostPayload
	addComment(input: [AddCommentInput!]!): AddCommentPayload
	updateComment(input: UpdateCommentInput!): UpdateCommentPayload
	deleteComment(filter: CommentFilter!): DeleteCommentPayload
}


```

**Comment by smkhalsa** [comment] 2021-08-01 00:05
duplicate of https://github.com/gql-dart/ferry/issues/203

**Closed by smkhalsa** 2021-08-01 00:05 UTC

**Comment by aliak00** [comment] 2021-08-01 09:18
@smkhalsa I tried getting the alpha release of the gql library (0.13.1-alpha....) as it seems that has the commit you speak of? But I'm not sure. But that doesn't work either.

Is the fix not out or is there some way I can test the fix?

**Comment by aliak00** [comment] 2021-08-01 09:27
I also tried in pubspec.yaml:
```


dependency_overrides:
  gql:
    git:
      url: git@github.com:gql-dart/gql.git
      ref: master
      path: gql/
```

But to no avail.

**Comment by smkhalsa** [comment] 2021-08-01 09:27
Did you add dependencies for the alpha versions of gql_build and gql_code_builder?

You'll also need to rebuild, of course

**Comment by aliak00** [comment] 2021-08-01 09:28
Ok, will try! Thanks

**Comment by aliak00** [comment] 2021-08-01 09:33
@smkhalsa yep, adding the alpha versions of those other packages did the trick! Thank you. Appreciate the help!

**Comment by henriqueArrazao** [comment] 2022-01-05 14:40
@smkhalsa could you put here your pubspec.yaml file? I'm facing some issues too
