### ISSUE TITLE
Input types and enums not being imported properly when the schema files doesn't end in .graphql

### ISSUE THREAD

**Issue by j-waters** [gql-dart/ferry#287] opened 2021-10-03 00:16 UTC
I've discovered the reason why my code was failing in #264 - my schema file was named `schema.gql`, which apparently breaks things. I wasn't able to use input types or enums in my queries, using either would result in:
```
[SEVERE] built_value_generator:built_value on lib/graphql/__generated__/fragments.data.gql.dart:
Error in BuiltValueGenerator for abstract class GFileFragmentData implements Built<GFileFragmentData, dynamic>, GFileFragment.
Please make the following changes to use BuiltValue:

1. Make field type have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
```

Renaming the schema `schema.graphql` seems to have fixed the issue

**Comment by smkhalsa** [comment] 2021-10-03 05:46
Yes, all graphql files must end in .graphql

Closing since this is the expected behavior

**Closed by smkhalsa** 2021-10-03 05:46 UTC
