### ISSUE TITLE
Outdated `analyzer` dependency on ferry_generator

### ISSUE THREAD

**Issue by QuirijnGB** [gql-dart/ferry#291] opened 2021-10-05 01:05 UTC
Analyzer dependency on the generator is outdated:
https://github.com/gql-dart/ferry/blob/master/packages/ferry_generator/pubspec.yaml#L18
Starting to get conflicts with other packages. 
Is there a reason it hasnt been updated in a while?

**Comment by QuirijnGB** [comment] 2021-10-05 04:30
Theres a dependency on [gql_code_builder](https://github.com/gql-dart/gql).

**Comment by ambiguous48** [comment] 2021-11-03 20:02
> How are others working around this issue? I'm reluctant to do a dependency_override in case that breaks it just wondering if anyone else has found a workaround for this

Did you end up doing it? If so, did you face any issues?

**Comment by KieranLafferty** [comment] 2021-11-03 20:09
> > How are others working around this issue? I'm reluctant to do a dependency_override in case that breaks it just wondering if anyone else has found a workaround for this
> 
> Did you end up doing it? If so, did you face any issues?

Yea I ended up adding the following to my pubspec and everything has been working from what I can tell

```
dependency_overrides:
  ### Required due to https://github.com/gql-dart/ferry/issues/291
  analyzer: ^2.7.0
```

I'm curious if this repo is going will continue actively maintained going forward? Reason I ask is that the repo was receiving nearly daily commits up until September 9th then nothing since. Is there a dev branch or new project I'm not aware of? 

Hope that my question doesn't come across the wrong way I'm genuinely curious what the future of the repository is going to be. I **really** appreciate all of the hard work everyone has put into this repo

**Comment by smkhalsa** [comment] 2021-11-03 22:10
duplicate of https://github.com/gql-dart/ferry/issues/282

> I'm curious if this repo is going will continue to be actively maintained going forward?
I plan to continue to maintain ferry on a best-effort basis.

**Closed by smkhalsa** 2021-11-03 22:10 UTC
