### ISSUE TITLE
Nullable item in list causes deserialization error

### ISSUE THREAD

**Issue by tommyle** [gql-dart/ferry#329] opened 2022-02-22 19:05 UTC
Should ferry be able to handle nulls in lists?

My schema is defined as:

```
type User {
    id: Int!
    name: String!
}

type UsersResponse {
    users: [User]!
}
```

The response contains a list of users, which can contain nulls.

Ex response: 
```
{
  "data": [
    {
      "id": 1,
      "name": "bob"
    },
    null,
    {
      "id": 2,
      "name": "alice"
    }
  ]
}
```

I get an error deserializing the response:
```
_TypeError (type 'Null' is not a subtype of type 'GUserData_getUsers_users')
```

**Comment by smkhalsa** [comment] 2022-03-06 19:32
This looks like a duplicate of https://github.com/gql-dart/ferry/issues/219. Feel free to reopen if you believe otherwise.

**Closed by smkhalsa** 2022-03-06 19:32 UTC
