### ISSUE TITLE
Operation widget: loading stays 'true' after I run it again with different parameters

### ISSUE THREAD

**Issue by alexboulay** [gql-dart/ferry#208] opened 2021-06-18 10:59 UTC
I have a search widget that accepts keywords. Upon the first request, everything works as expected: `loading` is set to true and I can show the user a loading Widget. Once data comes in, loading is set to `false` and then I show the user the result of their search. However, if the user changes their query and enters another keyword for exemple, the query is ran again but `loading` is always `false`. 

Am I missing something? How will I be able to show the user that their query is running? My server responds fairly fast but it looks very strange UI-wise when the results just change out of no where without any indicators.

Thanks in advance

**Comment by smkhalsa** [comment] 2021-06-18 13:42
Duplicate of #128. PRs welcome

**Closed by smkhalsa** 2021-06-18 13:42 UTC
