### ISSUE TITLE
Unable to use build_runner 2.0.0 (null safe version) along with ferry

### ISSUE THREAD

**Issue by dopecoder** [gql-dart/ferry#177] opened 2021-04-20 20:34 UTC
Hi @smkhalsa @knaeckeKami,
I'm unable to update the build_runner package to 2.0.0 (null safe version) as its not compatible with ferry

```
$ flutter pub get
Running "flutter pub get" in app...                    
Because build_runner >=2.0.0 depends on code_builder ^4.0.0 and ferry_generator 0.4.1-0.1.nullsafety.0 depends on code_builder ^3.7.0, build_runner >=2.0.0 is incompatible with ferry_generator 0.4.1-0.1.nullsafety.0.

And because no versions of ferry_generator match >0.4.1-0.1.nullsafety.0 <0.5.0, build_runner >=2.0.0 is incompatible with ferry_generator ^0.4.1-0.1.nullsafety.0.
So, because app depends on both ferry_generator ^0.4.1-0.1.nullsafety.0 and build_runner ^2.0.0, version solving failed.
pub get failed (1; So, because app depends on both ferry_generator ^0.4.1-0.1.nullsafety.0 and build_runner ^2.0.0, version solving failed.)
exit code 1
```

Would it be possible to update the packages so that ferry is compatible with build_runner - 2.0.0

**Comment by knaeckeKami** [comment] 2021-04-21 19:02
did you check if it's an actual incompatibility or just caused by version constraints?

i.e. does does work if you force the version with dependency_overrides?

**Comment by dopecoder** [comment] 2021-04-21 19:42
It seems to be an actual incompatibility. I tried using dependency overrides, this is the following overrides i had to use

```
dependency_overrides:
  build_runner: ^2.0.0    # Null Safe build_runner package
  code_builder: ^4.0.0    # tried with 3.7.0, but throws error saying that the code_builder package is not null safe
  build_config: ^1.0.0.   # required for auto_route package
```

When I run build on the above overrides, I get the following errors : 

```
-> flutter pub run build_runner build? (d:delete-conflicting-outputs): d
[INFO] Generating build script...
[INFO] Generating build script completed, took 457ms

[INFO] Creating build script snapshot......
[WARNING] stderr: ../WD/dev-libs/flutter/.pub-cache/hosted/pub.dartlang.org/gql_build-0.2.0-nullsafety.0/lib/src/utils/writer.dart:22:16: Error: Too many positional arguments: 0 allowed, but 3 found.
[WARNING] stderr: Try removing the extra positional arguments.
[WARNING] stderr:     DartEmitter(
[WARNING] stderr:                ^
[WARNING] stderr: ../WD/dev-libs/flutter/.pub-cache/hosted/pub.dartlang.org/code_builder-4.0.0/lib/src/emitter.dart:73:3: Context: Found this candidate, but the arguments don't match.
[WARNING] stderr:   DartEmitter(
[WARNING] stderr:   ^^^^^^^^^^^
[WARNING] stderr: ../WD/dev-libs/flutter/.pub-cache/hosted/pub.dartlang.org/gql_build-0.2.0-nullsafety.0/lib/src/serializer_builder.dart:101:33: Error: Too many positional arguments: 0 allowed, but 3 found.
[WARNING] stderr: Try removing the extra positional arguments.
[WARNING] stderr:     final _emitter = DartEmitter(
[WARNING] stderr:                                 ^
[WARNING] stderr: ../WD/dev-libs/flutter/.pub-cache/hosted/pub.dartlang.org/code_builder-4.0.0/lib/src/emitter.dart:73:3: Context: Found this candidate, but the arguments don't match.
[WARNING] stderr:   DartEmitter(
[WARNING] stderr:   ^^^^^^^^^^^
[WARNING] stderr: ../WD/dev-libs/flutter/.pub-cache/hosted/pub.dartlang.org/injectable_generator-1.2.2/lib/generators/injectable_config_generator.dart:64:20: Error: Too many positional arguments: 0 allowed, but 3 found.
[WARNING] stderr: Try removing the extra positional arguments.
[WARNING] stderr:         DartEmitter(Allocator.simplePrefixing(), true, usesNullSafety);
[WARNING] stderr:                    ^
[WARNING] stderr: ../WD/dev-libs/flutter/.pub-cache/hosted/pub.dartlang.org/code_builder-4.0.0/lib/src/emitter.dart:73:3: Context: Found this candidate, but the arguments don't match.
[WARNING] stderr:   DartEmitter(
[WARNING] stderr:   ^^^^^^^^^^^
[WARNING] stderr: ../WD/dev-libs/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route_generator-1.0.2/lib/src/code_builder/library_builder.dart:58:30: Error: Too many positional arguments: 0 allowed, but 3 found.
[WARNING] stderr: Try removing the extra positional arguments.
[WARNING] stderr:   final emitter = DartEmitter(Allocator.simplePrefixing(), true, true);
[WARNING] stderr:                              ^
[WARNING] stderr: ../WD/dev-libs/flutter/.pub-cache/hosted/pub.dartlang.org/code_builder-4.0.0/lib/src/emitter.dart:73:3: Context: Found this candidate, but the arguments don't match.
[WARNING] stderr:   DartEmitter(
[WARNING] stderr:   ^^^^^^^^^^^
[WARNING] stderr: ../WD/dev-libs/flutter/.pub-cache/hosted/pub.dartlang.org/gql_build-0.2.0-nullsafety.0/lib/src/allocators/gql_allocator.dart:35:14: Error: A value of type 'String?' can't be returned from a function with return type 'String' because 'String?' is nullable and 'String' isn't.
[WARNING] stderr:       return symbol;
[WARNING] stderr:              ^
[WARNING] stderr: ../WD/dev-libs/flutter/.pub-cache/hosted/pub.dartlang.org/gql_build-0.2.0-nullsafety.0/lib/src/allocators/gql_allocator.dart:39:38: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
[WARNING] stderr:       _imports.putIfAbsent(reference.url, () => null);
[WARNING] stderr:                                      ^
[INFO] Creating build script snapshot... completed, took 6.0s

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

pub finished with exit code 78
```

For code_builder-4.0.0. there seems to be changes in the interface. Would it be possible to use any other combination of dependency_overrides?

**Comment by knaeckeKami** [comment] 2021-04-21 22:20
Ah yeah, it's mentioned in the Changelog of [code_builder](https://pub.dev/packages/code_builder/changelog):

> Changed the DartEmittor constructor to use named optional parameters.

I'll have a look, probably this weekend

**Comment by smkhalsa** [comment] 2021-04-22 10:29
Please see https://github.com/gql-dart/gql/pull/221

**Comment by SimonErich** [comment] 2021-04-24 17:30
Hey guys, I am having the same issue right now.
@dopecoder did you make it work somehow in the meantime?
I am having trouble and I am stuck until this gets merged.

**Comment by knaeckeKami** [comment] 2021-04-24 17:32
Is there a reason why you need to be in build_runner 2.0.0 already?

**Comment by SimonErich** [comment] 2021-04-24 17:34
I would like to switch my application to null safety and otherwise I get the `null-safety` warning.

**Comment by knaeckeKami** [comment] 2021-04-24 17:40
Ok, but you can switch your app to null safety even on `build_runner ^1.0.0`. That latest version of freezer already generates null safe code. It just that build_runner itself runs still on non-null safe mode, but it can still generate null safe code.
Its not something that you would get stuck on.

**Comment by SimonErich** [comment] 2021-04-24 18:14
Thanks @knaeckeKami for getting back. I think I just cannot get a dependency combination working, where it works.
The furthest I got was with this:

```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_platform: ^1.0.0-nullsafety
  json_serializable: ^4.1.1

  # ferry
  gql_link: ^0.4.0-nullsafety.3
  gql_http_link: ^0.4.0-nullsafety.1
  ferry: ^0.10.1-0.1.nullsafety.0
  ferry_hive_store: ^0.4.1-0.1.nullsafety.0
  ferry_flutter: ^0.5.1-0.1.nullsafety.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  get_it: ^6.1.1
  intl: ^0.17.0
  i18n_extension: ^4.0.3
  gql_code_builder: ^0.2.0-nullsafety.0
  build_runner:

dev_dependencies:
  flutter_test:
    sdk: flutter
  gql_build: ^0.2.0-nullsafety.0
  ferry_generator: ^0.4.1-0.1.nullsafety.0
  analyzer: 1.5.0
```

Unfortunately, when running builder_runner I get
```
[SEVERE] json_serializable:json_serializable on lib/packages/chat/rooms/hooks/use_get_rooms_query/graphql/get_rooms_listing_fragment.var.gql.dart:

This builder requires Dart inputs without syntax errors.
However, package:mqtchat/packages/chat/rooms/hooks/use_get_rooms_query/graphql/get_rooms_listing_fragment.var.gql.dart (or an existing part) contains the following errors.
get_rooms_listing_fragment.var.gql.dart:23:38: This requires the 'non-nullable' language feature to be enabled.
```

And these two types of files are not being generated anymore:
```import 'package:mqtchat/serializers.gql.dart' as _i1;

part 'get_rooms.data.gql.g.dart';```

Does anyone have a suggestion or an example of a working pubspec version combination?

**Comment by knaeckeKami** [comment] 2021-04-24 19:21
If you use null safe code, you need to set the `sdk` version to `>=2.12.0`. Note that you either need to migrate your project or or add 
`// @dart=2.11`
add the beginning of every file which is not migrated to null safety.

**Comment by antholeole** [comment] 2021-04-29 06:26
@SimonErich you should be able to get it working with `build_runner` 1.x.x if you move `build_runner` to a dev dependency - that way, the code in build runner is not included in your app and thus does not need to be null safe.

**Comment by zoechi** [comment] 2021-05-05 09:43
Other packages depend on build_runner 2.x

**Comment by smkhalsa** [comment] 2021-05-11 15:44
Fixed in the latest version of `gql_build` / `ferry_generator`

**Closed by smkhalsa** 2021-05-11 15:44 UTC
