### ISSUE TITLE
Show Progress Indicator on Refetch? response.loading only true on initial fetch.

### ISSUE THREAD

**Issue by mdrideout** [gql-dart/ferry#240] opened 2021-08-18 19:37 UTC
Hey Everyone,

I am coming from a Future based graphql client. When I am refetching for updated data, I like to show the user a progress indicator.

With the Ferry GraphQL plugin, I am using `gqlClient.requestController.add(gqlRequest);` to refetch the data ([as seen here in the documentation](https://ferrygraphql.com/docs/pagination#refetching)).

I have seen that with StreamBuilder, it is suggested to use `ConnectionState` to determine whether to show a progress indicator. However, I do not seem to be able to access this from the [Operation widget](https://ferrygraphql.com/docs/flutter-operation-widget), or from the **OperationResponse** object returned from the `.listen()` function.

I can use the following to show the loader, **but it only works for the first request**
```dart
          if (response.loading) {
            return Center(child: CircularProgressIndicator());
          }
```

This does not work for subsequent refetches using `gqlClient.requestController.add(gqlRequest);`

Example client and request:
```dart
  final gqlClient = initGqlClient('http://localhost:3000/api/graphql');
  var gqlRequest = GgetAllItemsReq((b) => b..fetchPolicy = FetchPolicy.NetworkOnly);
```

If anyone has a code example that would work it would be much appreciated. My goal is for the progress indicator to display again for each refetch. 

There is currently a TODO inside `operation_response.dart` for the loading getter. Unsure if the widget, as coded, is capable of determining if a refetch is happening.
```dart
  // TODO: is there a better way to implement loading?
  bool get loading => linkException == null && data == null;
```

**Comment by smkhalsa** [comment] 2021-08-18 21:31
duplicate of #128

**Closed by smkhalsa** 2021-08-18 21:31 UTC
