### ISSUE TITLE
How to access extensions from data response

### ISSUE THREAD

**Issue by tiennano** [gql-dart/ferry#243] opened 2021-08-24 02:52 UTC
`{
  "data": {
    "__typename": "Mutation",
    "requestLogin": {
      "__typename": "RequestLoginResponse",
      "isNew": false,
      "token": "+84966962710"
    }
  },
  "extensions": {
    "x-debug-otp": "100136"
  }
}`

**Comment by smkhalsa** [comment] 2021-08-24 08:01
duplicate of https://github.com/gql-dart/ferry/issues/117

**Closed by smkhalsa** 2021-08-24 08:01 UTC
